name=Ultrasonic-Sensor
version=1.0
author=Tomoji Kanae
maintainer=Tomoji Kanae <github.com/TomojiKanae>
sentence=a ultrasonic sensor library
paragraph=Supports HC-SR04 in Arduino UNO and ESP32
category=Device Control
architectures=*